# Generated by Django 5.1.2 on 2024-12-26 16:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haritalar', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='complaint_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='trafiksorunu',
            name='gorsel',
            field=models.ImageField(blank=True, null=True, upload_to='sorun_gorselleri/'),
        ),
        migrations.AlterField(
            model_name='trafiksorunu',
            name='kullanici',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trafik_sorunlari', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='yorum',
            name='kullanici',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='haritalar_yorumlar', to=settings.AUTH_USER_MODEL),
        ),
    ]
