# Generated by Django 5.1.4 on 2024-12-29 17:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haritalar', '0003_delete_complaint_alter_trafiksorunu_kullanici_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='trafiksorunu',
            name='oy_verenler',
            field=models.ManyToManyField(blank=True, related_name='oy_verilen_sorunlar', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='trafiksorunu',
            name='kategori',
            field=models.CharField(choices=[('Yol Çalışması', 'Yol Çalışması'), ('Trafik Kazası', 'Trafik Kazası'), ('Araç Arızası', 'Araç Arızası'), ('Hatalı Park', 'Hatalı Park'), ('Aşırı Hız', 'Aşırı Hız'), ('Trafik Lambası Arızası', 'Trafik Lambası Arızası'), ('Yaya Geçidi İhlali', 'Yaya Geçidi İhlali'), ('Tehlikeli Sürüş', 'Tehlikeli Sürüş'), ('Şerit İhlali', 'Şerit İhlali'), ('Gürültü Kirliliği', 'Gürültü Kirliliği')], max_length=255),
        ),
    ]
