# Generated by Django 5.1.4 on 2025-01-12 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haritalar', '0004_trafiksorunu_oy_verenler_alter_trafiksorunu_kategori'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trafiksorunu',
            name='kategori',
            field=models.CharField(choices=[('Yol Çalışması', 'Yol Çalışması'), ('Trafik Kazası', 'Trafik Kazası'), ('Radar', 'Radar'), ('Sel Baskını', 'Sel Baskını'), ('Heyelan', 'Heyelan'), ('Trafik Lambası Arızası', 'Trafik Lambası Arızası'), ('Yolda Çökme', 'Yolda Çökme'), ('Vahşi Hayvan Çıkabilir', 'Vahşi Hayvan Çıkabilir')], max_length=255),
        ),
    ]
