# Generated by Django 5.1.2 on 2024-12-26 16:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kullanicilar', '0003_complaint'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sorun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kategori', models.CharField(max_length=255)),
                ('konum', models.CharField(max_length=255)),
                ('aciklama', models.TextField()),
                ('enlem', models.FloatField()),
                ('boylam', models.FloatField()),
                ('tarih', models.DateTimeField(auto_now_add=True)),
                ('gorsel', models.ImageField(blank=True, null=True, upload_to='sorun_gorselleri/')),
                ('kullanici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Yorum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icerik', models.TextField()),
                ('tarih', models.DateTimeField(auto_now_add=True)),
                ('kullanici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kullanicilar_yorumlar', to=settings.AUTH_USER_MODEL)),
                ('sorun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yorumlar', to='kullanicilar.sorun')),
            ],
        ),
        migrations.DeleteModel(
            name='Complaint',
        ),
    ]
