# Generated by Django 5.1.2 on 2024-12-27 12:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kullanicilar', '0004_sorun_yorum_delete_complaint'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='sorun',
            name='kullanici',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sorunlar', to=settings.AUTH_USER_MODEL),
        ),
    ]
