# Generated by Django 5.1.4 on 2024-12-27 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kullanicilar', '0005_alter_sorun_kullanici'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yorum',
            name='sorun',
        ),
        migrations.RemoveField(
            model_name='yorum',
            name='kullanici',
        ),
        migrations.DeleteModel(
            name='Sorun',
        ),
        migrations.DeleteModel(
            name='Yorum',
        ),
    ]
